language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install .
  - pip install python-coveralls pytest-cov
script: py.test --cov=pypac tests/
after_success:
  - coveralls
